version: '3.8'

services:
  web:
    build: .
    image: windy007008/note-web-2:latest
    ports:
      - "444:444"  
    volumes:
      - ./instance:/app/instance  # 使用命名卷
      - ./static:/app/static  # 挂载静态文件目录
      - ./templates:/app/templates  # 挂载模板目录
      - ./app.py:/app/app.py  # 挂载主程序文件
    environment:
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - FLASK_ENV=development  # 标记为开发环境
    restart: always
    command: ["gunicorn", 
              "--workers", "4",
              "--timeout", "120",
              "--keep-alive", "5",
              "--max-requests", "1000",
              "--max-requests-jitter", "50",
              "--log-level", "debug",     # 开发环境使用 debug 级别
              "--access-logfile", "-",
              "--error-logfile", "-",
              "--bind", "0.0.0.0:444",
              "app:app"]
