version: '3.8'

services:
  web:
    build: .
    image: windy007008/web_note_3:latest
    ports:
      - "5000:5000"  
    volumes:
      - ./instance:/app/instance:rw  # 明确指定读写权限
    environment:
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - FLASK_ENV=development  # 标记为开发环境
    restart: always
    user: "1000:1000"  # 使用宿主机的UID:GID
    command: ["gunicorn", 
              "--workers", "4",
              "--timeout", "120",
              "--keep-alive", "5",
              "--max-requests", "1000",
              "--max-requests-jitter", "50",
              "--log-level", "debug",     # 开发环境使用 debug 级别
              "--access-logfile", "-",
              "--error-logfile", "-",
              "--bind", "0.0.0.0:5000",
              "app:app"]


volumes:
  instance: